### ISSUE TITLE
new mw extension system

### ISSUE THREAD

**Issue by Naleksuh** [InternationalScratchWiki/wiki-scratchsig#2]
This extension has only been updated once in the last 8 years and that a security fix. About time to modernize it

**Comment by jacob-g** [comment]
Shouldn't be too hard, all we really need is an extension.json.

**Comment by Naleksuh** [comment]
Yeah this is straightforward as all the hooks are in Scratchsig.php, however I am currently unable to test code for the next 4 days

**Comment by jacob-g** [comment]
New repo was created for this.
