### ISSUE TITLE
parse wikitext for sig

### ISSUE THREAD

**Issue by Naleksuh** [InternationalScratchWiki/wiki-scratchsig#3]
Wikitext cannot load images from arbitrary urls, so that part will likely remain HTML while the wikilinks and such are wikitext

**Comment by Naleksuh** [comment]
Wikitext I would recommend is something like:
`[[User:$1|$1]] ([[User_talk:$1#top|talk]] {{!}} [[Special:Contributions/$1|contribs]])`

**Comment by jacob-g** [comment]
The contents of the tag should be a valid Scratch username, which can only contain letters, numbers, and certain punctuation marks (and underscores can be replaced with spaces for Wiki consistency). There is no need to parse it as Wikitext give that `[` and `]` are *not* valid in Scratch usernames.

**Comment by Naleksuh** [comment]
I did not say parse *as* wikitext, I meant that the signature will be rendered via Wikitext instead of HTML

**Comment by jacob-g** [comment]
Oh, that makes more sense. How would the image be rendered though? The image isn't stored on the Wiki so you can't use the standard `[[File:whatever.png]]` for it.

**Comment by Naleksuh** [comment]
As I said in the OP, "Wikitext cannot load images from arbitrary urls, so that part will likely remain HTML while the wikilinks and such are wikitext"

**Comment by jacob-g** [comment]
New repo was created for this.
